services:
  web:
    image: oshi-frontend-service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    env_file:
      - ./server_data/env_files/.env # Load environment variables from external .env file if available
